---
output: 
  officedown::rdocx_document:
    mapstyles:
      Normal: ['First Paragraph']
---

<!-- As a benefit to our readers, please provide concise and insightful sentences that identify "What is Known" about your topic and "What the Study Adds" to the literature. These sentences should be limited to 5 inclusively. This should NOT be a summary, but referenced in a bulleted format first listing the "What is Known" followed by the "What the Study Adds". Please do not include references. Please upload a Word document version of your points as a supplemental file; it should not be included in the main manuscript document.  -->

**What is Known**

- Missing data must be imputed in order to fit many standard modeling algorithms used for risk prediction. The prognostic accuracy of these prediction models depends on the imputation strategy. Imputation to the mean is often used in applied practice. 

<br> 

**What the Study Adds**

- We assessed how applying strategies other than imputation to the mean to impute missing values would impact the prognostic accuracy of downstream risk prediction models, i.e., models fitted to the imputed data. Our results show that many imputation strategies can improve model prognosis relative to using imputation to the mean.

- We measured imputation accuracy as well as prognostic accuracy of downstream risk prediction models using both single and multiple imputation techniques. Our results show that single imputation often has higher accuracy but multiple imputation often leads to greater prognostic accuracy of downstream models. 
